### ISSUE TITLE
API requires passing the referrer

### ISSUE THREAD

**Issue by harpster604** [waldoj/frostline#6]
Does this still work? I'm getting "too many API errors" and it doesn't do anything. I tried to manually access the API link and it seems to return a 504 gateway timeout.

**Comment by waldoj** [comment]
Ah, I'm glad you caught that. They've added a referrer check to their API. I've retitled this issue, and I'll modify Frostline to pass `http://planthardiness.ars.usda.gov/PHZMWeb/` as the referrer.

**Comment by waldoj** [comment]
All set! Thanks for this, @harpster604.

**Comment by webmaven** [comment]
:tada:

**Comment by harpster604** [comment]
So it was working fine when I tested it after the last fix, but now that I actually need to run it, I'm getting errors again.

```
http://planthardiness.ars.usda.gov/PHZMWeb/ZipProxy.ashx?ZipCode=00705
‽http://planthardiness.ars.usda.gov/PHZMWeb/ZipProxy.ashx?ZipCode=00610
‽http://planthardiness.ars.usda.gov/PHZMWeb/ZipProxy.ashx?ZipCode=00612
‽http://planthardiness.ars.usda.gov/PHZMWeb/ZipProxy.ashx?ZipCode=00601
‽http://planthardiness.ars.usda.gov/PHZMWeb/ZipProxy.ashx?ZipCode=00602
‽http://planthardiness.ars.usda.gov/PHZMWeb/ZipProxy.ashx?ZipCode=00603
‽http://planthardiness.ars.usda.gov/PHZMWeb/ZipProxy.ashx?ZipCode=00703
‽http://planthardiness.ars.usda.gov/PHZMWeb/ZipProxy.ashx?ZipCode=00704
‽http://planthardiness.ars.usda.gov/PHZMWeb/ZipProxy.ashx?ZipCode=07675
‽http://planthardiness.ars.usda.gov/PHZMWeb/ZipProxy.ashx?ZipCode=07677
‽Too many API errors: halting.
```

From what I can see it looks like they changed the api from:
http://planthardiness.ars.usda.gov/PHZMWeb/ZipProxy.ashx
to
http://planthardiness.ars.usda.gov/PHZMWeb/secure/ZipProxy.ashx

But it still doesn't seem to be grabbing any data for me.

**Comment by webmaven** [comment]
@harpster604, see #7 and #8.
