### ISSUE TITLE
Rewrite system to use ArcGIS REST API

### ISSUE THREAD

**Issue by waldoj** [waldoj/frostline#8]
@iandees discovered [the ArcGIS service that powers USDA's API](http://ec2-50-18-250-209.us-west-1.compute.amazonaws.com/ArcGIS/rest/services/uspz/MapServer/identify?geometryType=esriGeometryPoint&geometry=-77.029994%2C38.886728&sr=4326&layers=all%3A0&time=&layerTimeOptions=&layerdefs=&tolerance=3&mapExtent=%7B%22xmin%22%3A-12047469.183214823%2C%22ymin%22%3A5904320.654971005%2C%22xmax%22%3A-11764346.430446668%2C%22ymax%22%3A6089604.011534184%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%7D%7D&imageDisplay=400%2C400%2C96&returnGeometry=true&maxAllowableOffset=&f=HTML). So that becomes the new place where we need to get data from.
- [ ] determine the density of lon/lat pairs to have adequate resolution to capture the contours of the zones, but not so dense as to issue wasteful queries
- [ ] modify the system to retrieve by lon/lat, rather than by ZIP
- [ ] figure out the proper file format in which to store the results of those queries for maximum utility

**Comment by kneath** [comment]
I'm not sure if you're still interested in updating this project, but I was in search of similar data and found out a ton of this stuff has changed locations (ex: the link above is broken now). It seems like the company that was hosting this data has shut down:

> Enhanced versions of these files were previously distributed by Climate Source, Inc., which closed its doors on February 1, 2017. The original files are now available free of charge on this site. However, they continue to be the property of Oregon State University, and are subject to OSU’s terms of use. 

Through some spelunking I've found [the raw data available for download](http://prism.oregonstate.edu/projects/plant_hardiness_zones.php) which includes a CSV of zip codes very similar to what this project used to provide. A quick excerpt:

```
zipcode,zone,trange,zonetitle
01001,6a,-10 to -5,6a: -10 to -5
01002,5b,-15 to -10,5b: -15 to -10
01003,5b,-15 to -10,5b: -15 to -10
01004,5b,-15 to -10,5b: -15 to -10
01005,5b,-15 to -10,5b: -15 to -10
01007,5b,-15 to -10,5b: -15 to -10
01008,5b,-15 to -10,5b: -15 to -10
```
Additionally, there are some shapefiles and gridfiles which I've yet to dive into. This data also seems to be free to use so long as you display OSU & USDA ARS logos, which should put down the data usage legality questions.

**Comment by waldoj** [comment]
Whoa!

**Comment by waldoj** [comment]
This issue is obviated by #10.

**Comment by webmaven** [comment]
@kneath, a belated "thank you so much" for bringing this to our attention! :dancer: :100:
