### ISSUE TITLE
Create new server with data

### ISSUE THREAD

**Issue by juansaavedrauy** [waldoj/frostline#9]
Hello,

We where using the data provided in the pages for this project. I see that it has now been removed from the repo. I'm just wondering if there are any plans for this or we just should take the data and mount it in another place.

The USDA API is _really_ bad and from the other issue, it does not seem likely that it will be accessible in the long term. 

Thanks.

**Comment by waldoj** [comment]
The data was removed out of concern that the private party to whom the USDA has provided a data licensing contract could take it upon themselves to take legal action. (Any such legal action would be groundless—they have no right to the exclusive use of public data—but it could happen nonetheless.) I don't plan to host the data here again. Also, the USDA's website rebuilt their CAPTCHA system explicitly for the purpose of blocking Frostline from working.

However, last month we figured out enough to get around that CAPTCHA (#8), though it remains to do the work to write the code to extract that data. When that's done, Frostline will work again.

**Comment by simonv3** [comment]
Hey @waldoj, let me know if I can help somehow. I have lots of angry feels right now and want to channel them for good.

**Comment by ericR-123** [comment]
Can I simply get a dict mapping either cities or zips to hardiness zones? Is that too much to ask from the entire internet? How is that not already available somewhere?

**Comment by waldoj** [comment]
This issue is obviated by #10.
